name = "directors-worker"
main = "src/index.ts"
compatibility_date = "2024-07-18"

[observability.logs]
enabled = true

# Assets configuration for SPA (handled by Vite)
[assets]
directory = "dist/client/client"
not_found_handling = "single-page-application"
binding = "ASSETS"

# D1 database binding (staging)
[[d1_databases]]
binding = "DB"
database_name = "bardon-lodge-directors-staging"
database_id = "c174aee0-da86-4d6d-a398-bba3caaebf45"
migrations_dir = "migrations"

# Production environment
[env.production]
name = "directors-worker-prod"

# Production routes
routes = [
  { pattern = "directors.bardonlodge.co.uk", "custom_domain" = true }
]

# Production D1 database
[[env.production.d1_databases]]
binding = "DB"
database_name = "bardon-lodge-directors-prod"
database_id = "1269cdf3-6f15-49e9-ac69-c09866e0f007"
migrations_dir = "migrations"

# Staging environment (explicit configuration)
[env.staging]
name = "directors-worker-staging"

# Staging routes (explicit)
routes = [
  { pattern = "staging-directors.bardonlodge.co.uk", "custom_domain" = true }
]

[[env.staging.d1_databases]]
binding = "DB"
database_name = "bardon-lodge-directors-staging"
database_id = "c174aee0-da86-4d6d-a398-bba3caaebf45"
migrations_dir = "migrations"
