name = "directors-worker"
main = "src/index.ts"
compatibility_date = "2024-07-18"

# Default environment (staging)
# Assets configuration for SPA (handled by Vite)
[assets]
not_found_handling = "single-page-application"
binding = "ASSETS"

# D1 database binding (staging)
[[d1_databases]]
binding = "DB"
database_name = "bardon-lodge-directors-staging"
database_id = "c174aee0-da86-4d6d-a398-bba3caaebf45"
migrations_dir = "migrations"

# Production environment
[env.production]
name = "directors-worker-prod"

# Production D1 database
[[env.production.d1_databases]]
binding = "DB"
database_name = "bardon-lodge-directors-prod"
database_id = "" # TODO: Replace with production database ID when created
migrations_dir = "migrations"

# Staging environment (explicit configuration)
[env.staging]
name = "directors-worker-staging"

[[env.staging.d1_databases]]
binding = "DB"
database_name = "bardon-lodge-directors-staging"
database_id = "c174aee0-da86-4d6d-a398-bba3caaebf45"
migrations_dir = "migrations"
